- name: Provision a systemd enabled CentOS container
  hosts: all

  roles:
    # Mask unecessary services and systemd setup
    - systemd-setup
    # Configure jounrald log forwarding
    - journald-setup