- name: Install packages
  package:
      name: "{{ packages }}"
      state: present

- name: Yum Clean
  command: yum clean all
  args:
    warn: false

- name: Remove Yum cache file
  file:
    path: "{{ yum_cache_file }}"
    state: absent